### PR TITLE
chore: add readme & typo fix

### PR DESCRIPTION
**Pull request by thepassle**
- Small typo fix in the app-lit component (`todo` -> `todos`)
- And added a `README.md` with some extra notes on how to install and use lit-html directives :)

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Looks good to me! :tada:

**Comment by thepassle** [comment]
Thanks! Any chance this could get published to npm soon too?

**Comment by ndom91** [comment]
Sorry only @FredKSchott has the rights afaik, but I'm sure he'll be on it as soon as possible.

**Comment by FredKSchott** [comment]
(late response: this was merged via v2.0.1 :)

**Comment by thepassle** [comment]
Thanku ❤️

**Pull request merged**
