### PR TITLE
fix: removed mention of Preact

### PR DESCRIPTION
**Pull request by ndom91**
Noticed Preact was still mentioned by name there although any template could have been chosen at that point. 

Figured I'd pick up another PR today too ;)

### CODE REVIEW

**Comment by FredKSchott** [comment]
ha, nice catch!

**Comment by FredKSchott** [comment]
Okay, I think it's ready to release! Feel free to get any last PRs in otherwise I'll release in the next hour

**Comment by ndom91** [comment]
> Okay, I think it's ready to release! Feel free to get any last PRs in otherwise I'll release in the next hour

I'll make a new gif for the README as soon as I can use it via `npx` as well. Just let me know once its up

**Comment by FredKSchott** [comment]
Done! https://www.npmjs.com/package/@pika/init

**Pull request merged**
