### PR TITLE
Windows fixes

### LINKED ISSUE #27: Bug: ENOENT on windows 10
Installer crashes after template selection with a `ENOENT` (no such file...) for the package.json

Works correctly when run in WSL.

Node version: `13.2.0`
NPM version: `6.13.1`

Console output:

```
PS H:\pika> npx snowpack-init snowpack
npx: installed 71 in 5.881s
? Please choose a template app-lit
The system cannot find the path specified.

Welcome to snowpack-init ✨

Creating app: snowpack
Template: app-lit

The system cannot find the path specified.
C:\Users\james\AppData\Roaming\npm-cache\_npx\5836\node_modules\snowpack-init\node_modules\jsonfile\index.js:70
      throw err
      ^

Error: H:\pika/snowpack/package.json: ENOENT: no such file or directory, open 'H:\pika/snowpack/package.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.readFileSync (C:\Users\james\AppData\Roaming\npm-cache\_npx\5836\node_modules\snowpack-init\node_modules\jsonfile\index.js:64:22)
    at C:\Users\james\AppData\Roaming\npm-cache\_npx\5836\node_modules\snowpack-init\dist-node\index.js:101:33
    at C:\Users\james\AppData\Roaming\npm-cache\_npx\5836\node_modules\snowpack-init\node_modules\shelljs\src\exec.js:127:9
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1023:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'H:\\pika/snowpack/package.json'
}
```

### PR DESCRIPTION
**Pull request by dustinsoftware**
Many fixes in this PR were required to get a successful run on Windows.

If you want to try this out today, run `npx dpm-snowpack-init`, where I've published this fork.

image

Fixes #27

### CODE REVIEW

**Comment by ndom91** [comment]
Unfortunately I don't have any windows systems to test this on. @FredKSchott ?

**Comment by FredKSchott** [comment]
I don’t either, but I can install a VM and try it out. The code LGTM though, thanks for the fixes @dustinsoftware

**Comment by ndom91** [comment]
Okay dont sweat it then, i can grab a loaner notebook from work tomorrow and try it there briefly, looks good to me too though.

**Comment by ndom91** [comment]
Okay so I can confirm it worked well on my colleagues win10 PC with git-bash. 

There is however, some new output that sneaks through since we had to get rid of redirecting `npm i` entirely to `/dev/null`. I searched for a while for any additional npm flags or tricks to completely silence `npm install` output, but it doesnt look like that's possible. 

There also doesnt seem to be a nice cross-platform way to redirect output to nowhere. Windows has a similar null file, where you can just redirect to NUL (i.e. ` > NUL`), but you would first have to do an ugly `if os.platform() === 'win32' ...` 

If anyone knows a nice way to redirect output to nowhere, or simply silence npm install completely I'm all ears :) 

See screenshot:

image

Looks good to merge though technically. @FredKSchott - should we clean up output first or go ahead like this?

**Comment by dustinsoftware** [comment]
Personally I don’t mind the npm output; it’s especially helpful if something goes wrong. But I can understand wanting to silence it..

**Comment by ndom91** [comment]
Yeah I dont really mind either, but I think we can all agree it looks more professional when you 100% control the output.

**Comment by FredKSchott** [comment]
Yea, I think this makes sense to merge as-is. It sounds like the npm team is planning work to quiet this up on their end. If we're already passing `--silent`, then I think it's fine to just wait for that work.

In a future PR, I'd be +1 on also outputting the command that is being run (in big, bold letters) before running it, so that the logs that *are* being output are given some context.

**Review by FredKSchott — APPROVED** [review]
LGTM

**Pull request merged**
